From f373510d6a2bd9b32967df1b465a6b547ac08a82 Mon Sep 17 00:00:00 2001
From: Florian Franzmann <bwlf@bandrate.org>
Date: Sun, 1 Dec 2019 18:42:36 +0100
Subject: [PATCH 30/35] Cleanup: catch exception by const reference

---
 tests.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tests.cpp b/tests.cpp
index 390c924..68bc7e2 100644
--- a/tests.cpp
+++ b/tests.cpp
@@ -233,7 +233,7 @@ int main()
             t.test4();
 		}
 		cout << "tests passed\n";
-	}catch(std::exception& e){
+	}catch(const std::exception& e){
 		cerr << "caught exception\n";
 		cerr << e.what() << "\n";
 		return 1;
-- 
2.24.0

